### ISSUE TITLE
Codalab Error

### ISSUE THREAD

**Issue by TobiasLee** [VALUE-Leaderboard/EvaluationTools#8]
Hello, I tried to submit the results to the codelab. 
I put the test results in a zip file, which contains yc2c, tvc results formatted as the sampled data.
Yet the codelab reports an error:
> WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"python2\": executable file not found in $PATH": unknown.

Any suggestions on this issue?

**Comment by jayleicn** [comment]
This error is related to the recent [update](https://github.com/codalab/codalab-competitions/issues/3263) in Codalab, we have fixed the issue.
